---
title: "Homework-7"
author: "Noah Backman"
date: "10/28/2021"
output: pdf_document
---

## Question 1: Textbook 7.1
```{r}
# init constants
m = 1000
n = 20
k = 1
mse = numeric(9)

# for each k trimming, add to list
while(k < 10){
  tmean = numeric(m)
  for(i in 1:m){
    # need from cauchy dist
    x = sort(rcauchy(n))
    tmean[i] = median(x[k+1:(n-k)]) / (n - 2*k)
  }
  
  mse[k] = mean(tmean^2)
  k = k + 1
}
# tabulate
rbind(mse)
```


## Question 2: Textbook 7.6
```{r}
# init constants
alpha = 0.05
n = 20
df = 2

UCL <- replicate(1000, expr = {
  x = rchisq(n, df)
  (n - 1) * var(x) / qchisq(alpha, df=n-1)
})

# Empirical confidence level
sum(UCL > 4) / 1000
mean(UCL > 4)

result = t.test(x, mu=1)
result$statistic
result$parameter
result$p.value
result$conf.int
result$estimate

```


## Question 3
```{r}
m = 1000
g = numeric(m)

for(i in 1:m){
  x1 = rnorm(1)
  x2 = rnorm(1)
  x3 = rgamma(1, 3, 2)
  x4 = rgamma(1, 3, 2)
  g[i] = abs((x1+x2)^2 - (x3+x4)^2)
}

(mce = mean(g))

```


## Question 4
```{r}
p = .6
alpha = 0.05
n = 20

pass = rep(n, n)
sample = rbinom(n,1,p)
prop.test(x=sample, n=pass, conf.level=.9)
# simulate UCL 
UCL = replicate(1000, expr = {
  x = rbinom(n, 1, p)
  (n-1) * var(x) / qchisq(p, n-1)
})

sum(UCL >.7)
mean(UCL > .7)

# t.test
x <- rnorm(n,mean=2)
result <- t.test(x,mu=1)
result$statistic
result$parameter
result$p.value
result$conf.int
result$estimate
```



## Question 5
```{r}
alpha = .05
p = .7
sample = rbinom(20,1,p)

m <- 10000 
ps <- numeric(m)
# simulate for p-values
for (j in 1:m) {
  x <- rnorm(20)
  ttest <- t.test(x, mu = p)
  ps[j] <- ttest$p.value
}
# calculate and print p and se
p.hat <- mean(p != alpha)
se.hat <- sqrt(p.hat * (1 - p.hat) / m)
print(c(p.hat, se.hat))

```