---
title: "Homework8"
author: "Rishi Gummakonda"
date: "11/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1 (7.2)


```{r}

## Example 7.9 (Empirical Power)
n <- 20
m <- 1000
mu0 <- 500
sigma <- 100
mu <- seq(350,650,10) #alternatives
M <- length(mu)
power <- numeric(M)
for( i in 1:M ){
  mu1 <- mu[i]
  pvalues <- replicate(m, expr = {
    #simulate under alternative mu1
    x <- rnorm(n,mean=mu1,sd=sigma)
    ttest <- t.test(x,alternative="two.sided",mu=mu0)
    ttest$p.value
  })
  power[i] <- mean(pvalues <= .05)
}
se <- sqrt(power*(1-power)/m)

# plot the empirical power curve
# adding vertical error bars at pi(theta) +/- 2se(pi(theta))

library(ggplot2)
df <- data.frame(mean=mu, power=power, upper=power+2*se, lower=power-2*se)
ggplot(df,aes(x=mean,y=power)) +
  geom_line()+
  geom_vline(xintercept=500,lty=2) +
  geom_hline(yintercept=c(0,.05),lty=1:2) +
  geom_errorbar(aes(ymin=lower, ymax=upper), width=0.2, lwd=1.5)


```

## Question 2 (7.3)

```{r }


## Example 7.9 (Empirical Power)
n <- seq(10,50,10)
m <- 1000
mu0 <- 500
sigma <- 100
mu <- seq(450,650,10) #alternatives
M <- length(mu)
power <- numeric(M)
for( i in 1:M ){
  mu1 <- mu[i]
  pvalues <- replicate(m, expr = {
    #simulate under alternative mu1
    x <- rnorm(n,mean=mu1,sd=sigma)
    ttest <- t.test(x,alternative="greater",mu=mu0)
    ttest$p.value
  })
  power[i] <- mean(pvalues <= .05)
}
se <- sqrt(power*(1-power)/m)

# plot the empirical power curve
# adding vertical error bars at pi(theta) +/- 2se(pi(theta))

library(ggplot2)
df <- data.frame(mean=mu, power=power, upper=power+2*se, lower=power-2*se)
ggplot(df,aes(x=mean,y=power)) +
  geom_line()+
  geom_vline(xintercept=500,lty=2) +
  geom_hline(yintercept=c(0,.05),lty=1:2) 
  #geom_errorbar(aes(ymin=lower, ymax=upper), width=0.2, lwd=1.5)



```

## Question 3 (11.1)

```{r}

### Example 11.1 (Metropolis-Hastings sampler)

    f <- function(x, sigma) {
        if (any(x < 0)) return (0)
        stopifnot(sigma > 0)
        return((x / sigma^2) * exp(-x^2 / (2*sigma^2)))
    }

    m <- 10000
    sigma <- 4
    x <- numeric(m)
    x[1] <- rchisq(1, df=1)
    k <- 0
    u <- runif(m)

    for (i in 2:m) {
        xt <- x[i-1]
        y <- rchisq(1, df = xt)
        num <- f(y, sigma) * dchisq(xt, df = y)
        den <- f(xt, sigma) * dchisq(y, df = xt)
        if (u[i] <= num/den) x[i] <- y else {
             x[i] <- xt
             k <- k+1     #y is rejected
             }
        }

    print(k)

    index <- 5000:5500
    y1 <- x[index]
    plot(index, y1, type="l", main="", ylab="x")

```

## Question 4 (11.2)

```{r}

f <- function(x, sigma) {
  if (any(x < 0)) return (0)
    stopifnot(sigma > 0)
  return((x / sigma^2) * exp(-x^2 / (2*sigma^2)))
}

m <- 10000
sigma <- 4
x <- numeric(m)
x[1] <- rchisq(1, df=1)
k <- 0
u <- runif(m)

for (i in 2:m) {
  xt <- x[i-1]
  y <- rgamma(1, xt)
  num <- f(y, sigma) * dgamma(xt, y)
  den <- f(xt, sigma) * dgamma(y, xt)
  if (u[i] <= num/den){
    x[i] <- y 
  }
  else {
    x[i] <- xt
    k <- k+1     #y is rejected
  }
}

print(k)

index <- 5000:5500
y1 <- x[index]
plot(index, y1, type="l", main="", ylab="x")

# the rejected k values increase for sigma=2
# there are more flat regions on graph
# the y axes scales down



```

