---
title: "Lab14"
author: "Rishi Gummakonda"
date: "10/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1 
from Example 7.11 in R Code


```{r}

#============#
#=== MCMC ===#
#============#
# Example 7.11
# Define the density function of Rayleigh distribution
f <- function(x, lambda, mu, v)
  {
  return(1 + lambda*(x - mu)^2 / v)^-(v+1/2)
}

m <- 10000
lambda <- 4
mu = 3 
v = 5

x <- numeric(m)
x[1] <- rchisq(1,df=1)
k <- 0
u <- runif(m)
for(i in 2:m){
  xt <- x[i-1]
  y <- rchisq(1,df=xt)
  num <- f(y, lambda, mu,v)*dchisq(xt,df=y)
  den <- f(xt,lambda, mu, v)*dchisq(y,df=xt)
  if (u[i]<= num/den) x[i] <- y
  else {
    x[i] <- xt
    k <- k+1 # y is rejected
  }
}

# Check how many y rejected
print(k)

# Plot the Markov chain x
plot(x, type="l")

# display a partial plot starting at index 5000:5500
index <- 5000:5500
y1 <- x[index]
plot(index,y1,type="l", main="", ylab="x")

# Check the distribution with QQ plot
b <- 2001 # discard the burnin sample
y <- x[b:m]
a <- ppoints(100)
QR <- sigma*sqrt(-2*log(1-a)) #quantiles of Rayleigh, check page 303
Q <- quantile(y,a)

qqplot(QR, Q, main="", cex=0.5, 
       xlab="Rayleigh Quantiles", ylab="Sample Quantiles")
abline(0,1)

hist(y,breaks="scott", main="", xlab="",freq=F)
lines(QR,f(QR,lambda, mu, v))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
