---
title: "Lab7"
author: "Rishi Gummakonda"
date: "9/23/2021"
output: pdf_document
---

```{r }

```


## QUESTION 1
```{r}
inv <- function(x,a,b){
  a*(-log(1-x))^(1/b)
}

n <- 1000
u <- runif(n)
x <- inv(u,2,3)
hist(x, probability = T)
curve(dweibull(x,3,2), add = T)
```


## QUESTION 2
```{r }
n <- 1000
u <- runif(n)

pdf <- c(0.1,0.2,0.3,0.4)
cdf <- cumsum(pdf)
x <- u

for (i in 1:n) {
  if (u[i]<=cdf[1]) 
    {
      x[i]=1
    }
  else if (u[i]>cdf[1] & u[i]<=cdf[2]) 
    {
      x[i] =2
    }
  
    else if (u[i]>cdf[2] & u[i]<=cdf[3]) 
    {
      x[i] =3
    }
  else  
    {
      x[i] =4
    }
  
}
table(x)

```

## Question 3
```{r}
n <- 1000
u <- runif(n)
pareto(x,l,k){
  l*x^(-1/k)
}

x<- pareto(u,4,100)
hist(x)

```

# Question 4
```{r}
inv.cdf1 <- function(x,a,m,b){
  a + sqrt(x*(b-a)*(m-b))
}

inv.cdf2 <- function(x,a,m,b){
  b - sqrt((1-x)*(b-a)*(b-m))
}

n <- 1000
u <- runif(n)
u <- runif(n)
x <- numeric(n)
for(i in 1:n){
  if(u[i] > 0 & u[i] < (1/3))  x[i] = inv.cdf1(u[i],0,1/3,1)
  else if(u[i] >= (1/3) & u[i] < 1) x[i] = inv.cdf2(u[i],0,1/3,1)
}

hist(x)
```


