---
title: "Lab 7"
author: "Hamza Ali"
date: "9/23/2021"
output: html_document
---

## Question 1

```{r}
inv <- function(x,a,b){
  a*(-log(1-x))^(1/b)
}

n <- 1000
u <- runif(n)
x <- inv(u,2,3)
hist(x, probability = T)
curve(dweibull(x,3,2), add = T)
```

## Question 2

```{r}
n <- 1000
u <- runif(n)
p <- c(0.1,0.2,0.3,0.4)
x4 <- as.integer(u > 1-p[4])
x3 <- as.integer(u > 1-sum(p[3:4]))
x2 <- as.integer(u > 1-sum(p[2:4]))
x1 <- as.integer(u > 1-sum(p[1:4]))
x <- x1+x2+x3+x4
a <- tabulate(x)
data.frame(1:4,p,a/1000)
```

## Question 3

```{r}
n <- 1000
u <- runif(n)
pareto(x,l,k){
  l*x^(-1/k)
}

x<- pareto(u,4,100)
hist(x)
```

## Question 4

```{r}
triangle <- function(a,m,b){
  #curve(2*x, xlim = c(a,b), col = "yellow") #IGNORE THIS LINE
  curve(2*(x-a)/((b-a)*(m-a)), xlim = c(a,m), add = T)
  curve(2*(b-x)/((b-a)*(b-m)), xlim = c(m,b), add = T)
  return(1)
}


n <- 1000
k <- 0         #counter for accepted
j <- 0         #iterations
y <- numeric(n)

while(k < n){
  u <- runif(1)
  j <- j+1
  x <- runif(1) # random variate from g
  if(-4.5*(x-0.33)^2 + 2>u){
    #we accept x
    k <- k+1
    y[k] <- x
  }
}

j
hist(y,ylim = c(0,2), freq = F)
triangle(a=0,m=1/3,b=1)


```

